### Upload Excel File
POST http://localhost:3030/api/planning/upload
Content-Type: multipart/form-data; boundary=----BOUNDARY

------BOUNDARY
Content-Disposition: form-data; name="file"; filename="sample_data.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./public/sample_data.xlsx
------BOUNDARY--

###
POST http://localhost:3030/api/planning/generate-sample
Content-Type: application/json

{
	  "planningStartDate": "2025-05-29",
      "minEarlyDeliveryDays": 7

}


###
POST http://localhost:3030/api/planning/optimize
Content-Type: application/json

{     
     "planningSystem":{}, 
     "populationSize": 250,
     "generations": 600,
     "mutationRate": 0.2,
     "crossoverRate": 0.8,
     "promiseDatePreference":0.7,
     "timingVarianceWeeks":3,
     "unnecessaryDelayPenalty":100,
     "perfectTimingBonus":50
}


###
GET http://localhost:3030/api/planning/download-sample
Content-Type: application/json

{
	 
}

###
POST http://localhost:3030/api/planning/optimize/stop
Content-Type: application/json

{
	 "fullJobId": "ed60d55e-139c-4b13-a4a8-a8bc0c49d0f7"
}
###
GET http://localhost:3030/api/planning/download-results
Content-Type: application/json

{
	 
}
